### ISSUE TITLE
Replace custom cache code

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/statsdb-interface#12]
I've had a look at the custom cache code written by @shacknetisp which appears to be a bit fragile and not too efficient. Especially the fact that there's a thread running is worrying me. That might be one of the causes of performance issues, due to the GIL limitations. The use of globals is also not desirable.

I'd like to replace it with [Flask-Cache](https://pythonhosted.org/Flask-Cache/). I'd like to hear opinions before making the change. It has support for several high-performance backends, but for now, the simple backend would do the job.

**Comment by TheAssassin** [comment]
Update: Flask-Cache is the old, dead project. I intended to suggest [Flask-Caching](https://flask-caching.readthedocs.io/en/latest/), which appears to be a fork that is still developed.

**Comment by zaquest** [comment]
GIL is not a concern since the server in use is single threaded anyway. It also doesn't seem to cause performance issues in any other way. However I think in general it might be advantageous to replace it.

**Comment by TheAssassin** [comment]
@zaquest are you [aware of what I'm talking about](https://github.com/red-eclipse/statsdb-interface/blob/master/statsdbinterface/function_cache.py#L39-L67)? @shacknetisp made a thread run in the background that should clean up the cache, but that's rather inefficient, and every time that thread is run the GIL is locked and the performance will suffer.

Replacing has the advantage that when we should ever move to another system and be able to run more than one process (you don't run Python apps multithreaded but rather in multiple processes), an external cache like Memcache can be used as a shared instance and will further speed up the application. At the moment, I'd use the filesystem cache, which will be quite fast to work with, and reduce the amount of RAM consumed by the server process. Heck, we might even put it in `/dev/shm`.

**Comment by zaquest** [comment]
Well, one thing that can cause problems there is the exit check which is run a bit too often, and I'm not even sure why it's needed. Otherwise, the cleaner runs once a minute, which is like once in eternity. The problems could arise if there were many request processing threads, but there are not.

**Comment by TheAssassin** [comment]
Due to how Python threads work however, that is pretty bad for performance, even if just run once every minute. Also, the stats don't change _that_ often, I assume it wouldn't have to run every minute. Also a cache purge doesn't seem to be necessary at all, and pretty much eliminates the advantages of the caching, because the current system can't cache for more than one minute. I guess in average the cache is only used up to ~30 seconds.

I'd rather cache the responses with a reverse proxy to be honest, that's a lot better for performance and would allow SSL termination.

**Comment by zaquest** [comment]
It only removes old entries, so it's capable of caching for arbitrary time periods.
