### ISSUE TITLE
Add an HTML dashboard

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/statsdb-interface#4]
This should provide an overview of recent data:
- Games
- Best/most used weapons
- Most played maps
- Most played servers
- Player leaderboards (see #5 )

**Comment by TheAssassin** [comment]
Does this issue propose porting the "old" statsdb-interface-1 dashboard?

**Comment by shacknetisp** [comment]
It is not necessary to port everything, for example the number of captures metrics are rather useless, but anything that is useful should be ported if possible. Separate tables based on time (7, 30, 90, etc days ago) may be nice, as was done with the old interface.
